"use client";
import Image from "next/image";
import Link from "next/link";
import { Search, SlidersHorizontal, Star, ArrowUpRight } from "lucide-react";
import { useMemo, useState } from "react";
import { therapists } from "@/lib/data";

export default function Therapists() {
  const [q,setQ]=useState(""); const [language,setLanguage]=useState("All"); const [max,setMax]=useState("100");
  const filtered=useMemo(()=>therapists.filter(t=>(`${t.name} ${t.specialty} ${t.languages.join(" ")}`).toLowerCase().includes(q.toLowerCase())&&(language==="All"||t.languages.includes(language))&&t.price<=Number(max)),[q,language,max]);
  return <main className="container-shell py-16 md:py-24">
    <div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-sm font-bold text-[#6b9698]">THERAPIST DIRECTORY</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.06em] sm:text-6xl">Find someone<br/>who gets it.</h1><p className="mt-5 max-w-xl leading-7 text-[#6c7c80]">Browse the prototype directory. Filter by language, price and focus, then open a profile to see the booking experience.</p></div><div className="rounded-2xl bg-[#e4eee9] px-4 py-3 text-sm font-semibold text-[#52676a]">{filtered.length} therapists available</div></div>
    <div className="mt-12 rounded-[30px] bg-white p-4 card-shadow md:p-5"><div className="grid gap-3 md:grid-cols-[1fr_180px_160px]"><div className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#829094]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, specialty or language" className="w-full rounded-2xl bg-[#f4f6f3] py-3.5 pl-11 pr-4 outline-none focus:ring-2 focus:ring-[#a6cfcd]"/></div><select value={language} onChange={e=>setLanguage(e.target.value)} className="rounded-2xl bg-[#f4f6f3] px-4 py-3.5 outline-none"><option>All</option><option>Nepali</option><option>English</option><option>Hindi</option></select><select value={max} onChange={e=>setMax(e.target.value)} className="rounded-2xl bg-[#f4f6f3] px-4 py-3.5 outline-none"><option value="100">Any price</option><option value="40">Up to €40</option><option value="45">Up to €45</option></select></div></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">{filtered.map(t=><article key={t.id} className="group rounded-[30px] bg-white p-5 card-shadow"><div className="flex gap-5"><div className="relative h-28 w-28 shrink-0 overflow-hidden rounded-2xl" style={{background:t.accent}}><Image src={t.image} alt={t.name} fill className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold">{t.name}</h2><p className="mt-1 text-sm font-semibold text-[#729a9d]">{t.specialty}</p></div><p className="text-right font-bold">€{t.price}<span className="block text-[10px] font-normal text-[#8a9699]">/ session</span></p></div><p className="mt-3 flex items-center gap-1 text-xs text-[#748388]"><Star size={13} fill="currentColor"/> {t.rating} · {t.reviews} reviews · {t.years} yrs</p></div></div><p className="mt-5 text-sm leading-6 text-[#65767b]">{t.bio}</p><div className="mt-4 flex flex-wrap gap-2">{t.languages.map(l=><span key={l} className="rounded-full bg-[#f3f6f3] px-3 py-1 text-xs font-semibold">{l}</span>)}</div><Link href={`/therapists/${t.id}`} className="mt-5 flex items-center justify-center gap-2 rounded-2xl bg-[#20373b] py-3 text-sm font-bold text-white">View profile <ArrowUpRight size={16}/></Link></article>)}</div>
    {!filtered.length&&<div className="py-24 text-center"><SlidersHorizontal className="mx-auto text-[#90a0a2]"/><p className="mt-4 font-semibold">No matches yet.</p><p className="mt-1 text-sm text-[#7a898c]">Try a broader search or language.</p></div>}
  </main>;
}