export const therapists = [
  {
    id: "maya-sharma",
    name: "Maya Sharma",
    title: "Licensed Clinical Psychologist",
    location: "Finland",
    specialties: ["Anxiety", "Stress", "Life transitions"],
    languages: ["English", "Hindi", "Nepali"],
    rating: 4.9,
    reviews: 48,
    price: 65,
    availability: "Available this week",
    image:
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "aarav-mehta",
    name: "Aarav Mehta",
    title: "Psychotherapist",
    location: "Finland",
    specialties: ["Relationships", "Anxiety", "Self-esteem"],
    languages: ["English", "Hindi"],
    rating: 4.8,
    reviews: 36,
    price: 60,
    availability: "Available tomorrow",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "anisha-gurung",
    name: "Anisha Gurung",
    title: "Counselling Psychologist",
    location: "Sweden",
    specialties: ["Depression", "Adjustment", "Anxiety"],
    languages: ["English", "Nepali"],
    rating: 5.0,
    reviews: 29,
    price: 55,
    availability: "Available this week",
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "daniel-wilson",
    name: "Daniel Wilson",
    title: "Clinical Psychologist",
    location: "Finland",
    specialties: ["Stress", "Burnout", "Depression"],
    languages: ["English"],
    rating: 4.9,
    reviews: 61,
    price: 70,
    availability: "Available today",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "priya-kapoor",
    name: "Priya Kapoor",
    title: "Mental Health Counsellor",
    location: "Germany",
    specialties: ["Anxiety", "Relationships", "Family"],
    languages: ["English", "Hindi", "Punjabi"],
    rating: 4.8,
    reviews: 42,
    price: 58,
    availability: "Available this week",
    image:
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "rohan-thapa",
    name: "Rohan Thapa",
    title: "Psychotherapist",
    location: "Netherlands",
    specialties: ["Life transitions", "Stress", "Identity"],
    languages: ["English", "Nepali"],
    rating: 4.9,
    reviews: 34,
    price: 62,
    availability: "Available tomorrow",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "sara-ahmed",
    name: "Sara Ahmed",
    title: "Counselling Psychologist",
    location: "Finland",
    specialties: ["Trauma", "Anxiety", "Depression"],
    languages: ["English", "Arabic"],
    rating: 4.9,
    reviews: 53,
    price: 68,
    availability: "Available this week",
    image:
      "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "ethan-miller",
    name: "Ethan Miller",
    title: "Clinical Counsellor",
    location: "Finland",
    specialties: ["Burnout", "Work stress", "Anxiety"],
    languages: ["English"],
    rating: 4.7,
    reviews: 31,
    price: 57,
    availability: "Available today",
    image:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "neha-joshi",
    name: "Neha Joshi",
    title: "Licensed Therapist",
    location: "Denmark",
    specialties: ["Relationships", "Self-esteem", "Anxiety"],
    languages: ["English", "Hindi"],
    rating: 4.9,
    reviews: 47,
    price: 63,
    availability: "Available this week",
    image:
      "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=800&q=85",
  },
];