"use client";
import { FormEvent,useState } from "react";
import Link from "next/link";
import { useRouter,useSearchParams } from "next/navigation";
import { ArrowLeft, Heart } from "lucide-react";
import { USER_KEY,NAME_KEY } from "@/lib/auth";

export default function Signup(){const router=useRouter();const params=useSearchParams();const next=params.get("next")||"/dashboard";const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");
function submit(e:FormEvent){e.preventDefault();if(password.length<6){setError("Use at least 6 characters for your password.");return}localStorage.setItem(USER_KEY,email);localStorage.setItem(NAME_KEY,name);window.dispatchEvent(new Event("therapeace-auth"));router.push(next);}
return <main className="container-shell grid min-h-[calc(100vh-72px)] place-items-center py-16"><div className="w-full max-w-md"><Link href="/" className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-[#65767b]"><ArrowLeft size={15}/> Back home</Link><form onSubmit={submit} className="rounded-[34px] bg-white p-7 card-shadow sm:p-9"><div className="grid h-11 w-11 place-items-center rounded-[14px] bg-[#9fcfd0]"><Heart size={18}/></div><h1 className="mt-7 text-3xl font-semibold tracking-tight">Create your space.</h1><p className="mt-2 text-sm leading-6 text-[#738286]">A simple account for bookings and your personal dashboard.</p><label className="mt-8 block text-sm font-semibold">Full name<input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 w-full rounded-2xl bg-[#f4f6f3] p-3.5 outline-none focus:ring-2 focus:ring-[#a6cfcd]"/></label><label className="mt-5 block text-sm font-semibold">Email<input value={email} onChange={e=>setEmail(e.target.value)} required type="email" className="mt-2 w-full rounded-2xl bg-[#f4f6f3] p-3.5 outline-none focus:ring-2 focus:ring-[#a6cfcd]"/></label><label className="mt-5 block text-sm font-semibold">Password<input value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} type="password" className="mt-2 w-full rounded-2xl bg-[#f4f6f3] p-3.5 outline-none focus:ring-2 focus:ring-[#a6cfcd]"/></label>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button className="mt-7 w-full rounded-2xl bg-[#20373b] py-3.5 font-bold text-white">Create account</button><p className="mt-6 text-center text-sm text-[#7a898c]">Already have an account? <Link href={`/login?next=${encodeURIComponent(next)}`} className="font-bold text-[#20373b]">Log in</Link></p></form></div></main>}
