"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { CalendarDays, Clock3, LogOut, Settings, Sparkles, UserRound, X } from "lucide-react";
import { BOOKING_KEY, NAME_KEY, USER_KEY, Booking } from "@/lib/auth";
import { useRouter } from "next/navigation";

export default function Dashboard(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [name,setName]=useState("there"); const [booking,setBooking]=useState<Booking|null>(null); const [ready,setReady]=useState(false);
 useEffect(()=>{const u=localStorage.getItem(USER_KEY);if(!u){router.replace("/login?next=/dashboard");return}setEmail(u);setName(localStorage.getItem(NAME_KEY)||u.split("@")[0]);const raw=localStorage.getItem(BOOKING_KEY);if(raw)setBooking(JSON.parse(raw));setReady(true)},[router]);
 function cancel(){localStorage.removeItem(BOOKING_KEY);setBooking(null)}
 function logout(){localStorage.removeItem(USER_KEY);localStorage.removeItem(NAME_KEY);window.dispatchEvent(new Event("therapeace-auth"));router.push("/")}
 if(!ready)return <main className="container-shell py-24"><div className="h-40 animate-pulse rounded-[30px] bg-[#e7ece8]"/></main>;
 return <main className="container-shell py-12 md:py-20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold text-[#6b9698]">YOUR SPACE</p><h1 className="mt-2 text-5xl font-semibold tracking-[-.06em]">Good to see you, {name.split(" ")[0]}.</h1><p className="mt-3 text-[#718084]">A simple overview of your support journey.</p></div><button onClick={logout} className="flex w-fit items-center gap-2 rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-semibold"><LogOut size={15}/> Log out</button></div>
 <div className="mt-10 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-[34px] bg-[#20373b] p-7 text-white md:p-9"><div className="flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-full bg-white/10"><CalendarDays size={19}/></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold">Upcoming</span></div>{booking?<><p className="mt-10 text-sm text-white/55">Your next session</p><h2 className="mt-2 text-3xl font-semibold">{booking.therapist}</h2><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-white/10 px-3 py-2">{booking.date}</span><span className="rounded-full bg-white/10 px-3 py-2 flex items-center gap-1"><Clock3 size={14}/>{booking.time}</span><span className="rounded-full bg-white/10 px-3 py-2">€{booking.price}</span></div><button onClick={cancel} className="mt-8 flex items-center gap-2 text-sm font-semibold text-white/60 hover:text-white"><X size={15}/> Cancel booking</button></>:<><h2 className="mt-10 text-3xl font-semibold">Nothing booked yet.</h2><p className="mt-3 max-w-md leading-7 text-white/60">When you're ready, browse the directory and choose someone who feels like a good fit.</p><Link href="/therapists" className="mt-7 inline-block rounded-full bg-[#9fcfd0] px-5 py-3 font-bold text-[#20373b]">Find a therapist</Link></>}</section>
 <section className="rounded-[34px] bg-white p-7 card-shadow md:p-9"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#e5eee9]"><UserRound size={19}/></div><h2 className="mt-7 text-2xl font-semibold">Profile</h2><p className="mt-6 text-xs font-bold uppercase tracking-widest text-[#8b989b]">Name</p><p className="mt-1 font-semibold">{name}</p><p className="mt-5 text-xs font-bold uppercase tracking-widest text-[#8b989b]">Email</p><p className="mt-1 break-all font-semibold">{email}</p><div className="mt-8 border-t border-black/5 pt-6"><div className="flex items-center gap-2 text-sm font-semibold"><Settings size={16}/> Account settings</div><p className="mt-2 text-xs text-[#8a9699]">Settings are part of the next product iteration.</p></div></section></div>
 <section className="mt-5 grid gap-5 md:grid-cols-3">{[["Explore","Find support that fits your language and context.","/therapists"],["Prepare","Bring one thing you want to talk about.","#"],["Reflect","Your dashboard keeps the experience simple.","#"]].map(([a,b,c])=><Link href={c} key={a} className="rounded-[28px] bg-white p-6 card-shadow hover:-translate-y-0.5"><Sparkles size={17}/><h3 className="mt-7 font-bold">{a}</h3><p className="mt-2 text-sm leading-6 text-[#718084]">{b}</p></Link>)}</section>
 </main>;
}